/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Head from "next/head";
import BlogPage from "../../BlogComponents/BlogPage";

const BlogPostPage = () => {
  return (
    <>
      <Head>
        <title>
          How Green Financing is Changing the Nigerian Market | Blog
        </title>
        <meta
          name="description"
          content="Explore how green financing is transforming the Nigerian market by supporting sustainable projects and fostering an eco-friendly economy."
        />
      </Head>
      <BlogPage />
    </>
  );
};

export default BlogPostPage;
