/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

const ArticleCard = ({ image, category, date, title, excerpt }) => {
  return (
    <article className="article-card">
      <Image
        src={image}
        alt={title}
        width={320}
        height={229}
        className="article-image"
      />
      <div className="article-content">
        <div className="article-meta">
          <span className="article-category">{category}</span>
          <span className="article-date">{date}</span>
        </div>
        <h3 className="article-title">{title}</h3>
        <p className="article-excerpt">{excerpt}</p>
      </div>
    </article>
  );
};

export default ArticleCard;
