/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

const BlogLayout = ({ children }) => {
  return (
    <div className="blog-layout">
      <Header />
      <main className="blog-main">{children}</main>
      <Footer />
    </div>
  );
};

export default BlogLayout;
