/**
 * This code was generated by Builder.io.
 */
import React from "react";
import BlogLayout from "./BlogLayout";
import BlogPost from "./BlogPost";
import RelatedArticles from "./RelatedArticles";

const BlogPage = () => {
  return (
    <BlogLayout>
      <BlogPost />
      <RelatedArticles />
    </BlogLayout>
  );
};

export default BlogPage;
