/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";
import Link from "next/link";

const Footer = () => {
  return (
    <footer className="site-footer">
      <div className="container">
        <div className="footer-content">
          <div className="footer-logo">
            <Image
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/5f2db473addf02eb07c504b670db5eecdf5e73b5ecacf15334f6c64b2333461d?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
              alt="Company icon"
              width={50}
              height={50}
              className="company-icon"
            />
            <Image
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d004a30f6ca3110498596271b43345c285ec41009c1bd549ffa7bbfa7e722e88?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
              alt="Company logo"
              width={226}
              height={49}
              className="company-logo"
            />
          </div>
          <div className="footer-links">
            <div className="link-block">
              <h3 className="block-heading">Quick Links</h3>
              <ul>
                <li>
                  <Link href="/about">About Us</Link>
                </li>
                <li>
                  <Link href="/services">Services</Link>
                </li>
                <li>
                  <Link href="/faqs">FAQs</Link>
                </li>
                <li>
                  <Link href="/careers">Careers</Link>
                </li>
                <li>
                  <Link href="/contact">Contact Us</Link>
                </li>
              </ul>
            </div>
            <div className="link-block">
              <h3 className="block-heading">Contact Information</h3>
              <ul>
                <li>Phone number</li>
                <li>Email Address</li>
                <li>Office Location</li>
              </ul>
            </div>
            <div className="link-block">
              <h3 className="block-heading">Follow us</h3>
              <div className="social-icons">
                <Link href="#">
                  <Image
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/717d4a724b6c37f4e4ddff87f745fa35f559d76fe317dc2fde7d048837bbae2d?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
                    alt="Facebook"
                    width={24}
                    height={24}
                  />
                </Link>
                <Link href="#">
                  <Image
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/b8ed253faecbb9bea6e53daad77e847f4894654631d9e4b0fa72b3936fc507af?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
                    alt="Twitter"
                    width={24}
                    height={24}
                  />
                </Link>
                <Link href="#">
                  <Image
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b5738f08224d0aaffe1777d3cff08796eadfb1d5686d3dbc90118589aed1771?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
                    alt="Instagram"
                    width={24}
                    height={24}
                  />
                </Link>
                <Link href="#">
                  <Image
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/313f16ce6520a3659abcd733c34096213842a4aabc639a6b4ea7da7703cf05e9?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
                    alt="LinkedIn"
                    width={24}
                    height={24}
                  />
                </Link>
              </div>
            </div>
          </div>
        </div>
        <div className="footer-bottom">
          <hr className="footer-divider" />
          <div className="footer-info">
            <div className="legal-links">
              <Link href="/terms">Terms of Service</Link>
              <Link href="/privacy">Privacy Policy</Link>
            </div>
            <p className="copyright">
              &copy; Copyright 2024 Orbit All rights reserved.
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
