/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Link from "next/link";
import Image from "next/image";

const Header = () => {
  return (
    <header className="site-header">
      <div className="container">
        <div className="header-content">
          <div className="logo-container">
            <Image
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/eb14d617fcf57a94f4d39b50b722bb24c6db318bb6c49502331a0c187817cf5c?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
              alt="Company icon"
              width={50}
              height={50}
              className="company-icon"
            />
            <Image
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/559e5f8a2f69e5175afb31f16c27fe9c969385c91b8289bb5b654aeb909a359d?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
              alt="Company logo"
              width={226}
              height={49}
              className="company-logo"
            />
          </div>
          <nav className="main-nav">
            <ul className="nav-links">
              <li>
                <Link href="/about">About Us</Link>
              </li>
              <li>
                <Link href="/services">Services</Link>
              </li>
              <li>
                <Link href="/faqs">FAQs</Link>
              </li>
              <li>
                <Link href="/contact">Contact Us</Link>
              </li>
              <li className="resources-dropdown">
                <Link href="/resources">Resources</Link>
                <Image
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/745f4a325798408d80543bbacf1852135593f5c0514bd614a697a7386fbb93c1?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
                  alt="Dropdown arrow"
                  width={24}
                  height={24}
                  className="dropdown-icon"
                />
              </li>
            </ul>
          </nav>
          <div className="cta-container">
            <Link href="/signup" className="cta-button">
              Sign up
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
