/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ArticleCard from "./ArticleCard";

const RelatedArticles = () => {
  const articles = [
    {
      id: 1,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/a86226b6102184efaaa2f0b36be5a042e62f4eab98bd621dd0afdf0495b7db52?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&",
      category: "EDUCATION",
      date: "July 16th, 2024",
      title: "New AI Tools Revolutionize Micro-lending",
      excerpt:
        "AI-powered algorithms analyze vast datasets to assess borrower creditworthiness swiftly and accurately, expanding access to micro-loans",
    },
    {
      id: 2,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/bbcf752bf870612652e8c8adec926d6f5685300158621962333e40e1959dc8bd?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&",
      category: "EDUCATION",
      date: "July 16th, 2024",
      title: "How Green Financing is Changing the Nigerian Market",
      excerpt:
        "Green financing initiatives in Nigeria aim to boost investments in renewable energy sources like solar and wind power.",
    },
    {
      id: 3,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/bbcf752bf870612652e8c8adec926d6f5685300158621962333e40e1959dc8bd?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&",
      category: "EDUCATION",
      date: "July 16th, 2024",
      title: "How Green Financing is Changing the Nigerian Market",
      excerpt:
        "Green financing initiatives in Nigeria aim to boost investments in renewable energy sources like solar and wind power.",
    },
  ];

  return (
    <section className="related-articles">
      <h2 className="section-title">Read more Articles</h2>
      <div className="article-grid">
        {articles.map((article) => (
          <ArticleCard key={article.id} {...article} />
        ))}
      </div>
    </section>
  );
};

export default RelatedArticles;
